### ISSUE TITLE
Activate Shortcode?

### ISSUE THREAD

**Issue by timothystewart6** [mixer/shortcode-oauth#7]
Is is possible to activate a shortcode programmatically ?

I am writing a server side application and I want to get a new access tokens programmatically.  I can easily call each step in the flow via REST calls except the UI to approve the shortcode. (https://mixer.com/go?code=SOMECODE)

I see that mixer.com/go APPROVE button calls
https://mixer.com/api/v1/oauth/shortcode/activate/SOMECODE
when you click approve but not sure this is a public API and if so it's not documented nor do I want to construct this call with cookies from being signed in. (Unless I can make this call using my `Client-ID` in my headers as well as a POST body with my `client_id` and `client_secret` 

Maybe I am thinking about this wrong but shouldn't I be able to get an access token using my client ID and secret - server side and get access tokens without needing to use the shortcode?  If not, is there a way to approve the shortcode I get back via a REST call?

Side note, I can already get a token back that expires in a year using implicit flow however this is something I will have to update in time.

Thank you!

**Comment by connor4312** [comment]
You can use the refresh token you get back from the exchange to programatically retrieve a new access token after it expires, using the [refresh](https://github.com/mixer/shortcode-oauth/blob/master/nodejs/src/shortcode.ts#L249) method. I think that gets you want you want.

**Comment by timothystewart6** [comment]
Thanks!  I am familiar with exchanging a refresh token for a new refresh token and access token.  I guess what I am looking for is an automated way to get the access token the first and subsequent times so I can do the entire shortcode flow without the need for UI.

Is there a way to approve the short code via API without using the UI?  I guess I was hoping for more of a service account with OAuth scopes.  My service doesn't have a UI and I have to do an OAuth flow to get a new access token (since they expire every 6 hours).

**Comment by ProbablePrime** [comment]
Hey,

OAuthing without UI breaks one of the principles of OAuth. The user is always in control of their account and you must use our UI to ask for permission to access their account.

If the shortcode entering itself is a problem, I would suggest using the more formalized flows such as the authentication code flow which requires only that the user hits Approve.

You can store your refresh and access tokens within a Database or storage system which will allow you to use the refresh token after obtaining just one access token per user.

**Comment by timothystewart6** [comment]
Thanks @ProbablePrime !  The challenge I am facing is that I am running a service and the service account needs OAuth scopes.  I am not taking any action on behalf of any other user however I am forced to get an OAuth token with the appropriate scopes in order to make REST calls to Mixer APIs for my service.

Your suggestion of storing and refreshing the token will work, however it still requires a UI the first time.  I guess I was hoping for something more like App-Auth, which isn't OAuth.

I guess I will just grab an implicit token and use it for a year and update at some point.  Thanks for the help.
